name: deploy to ec2 with docker
on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout branch
              uses: actions/checkout@v2

            - name: build image
              working-directory: .
              run: docker build -t jihokim2/order-be:latest .   

            - name: dockerhub login
              uses: docker/logi0n-action@v1
              with:
                username: ${{secrets.DOCKER_EMAIL}}
                password: ${{secrets.DOCKER_PASSWORD}}

            - name: push to dockerhub
              run: docker push jihokim2/order-be:latest