name: deploy to ec2 with jar

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: build jar
        working-directory: .
        run: |
          chmod 777 ./gradlew
          ./gradle bootJar

      - name: copy jar to ec2
        uses: appleboy/scp-action@master
        with:
          host: ec2-13-211-3-158.ap-southeast-2.compute.amazonaws.com
          username: ubuntu
#          pemkey를 통해  해당 인스턴스 접근
          key: ${{secrets.EC2_PEMKEY}}
          source: ./build/libs/*.jar
          target: "/home/ubuntu"